### ISSUE TITLE
git2r seg faults when trying to load after build - Centos 6 - vast-tools

### ISSUE THREAD

**Issue by stetner** [ropensci/git2r#287]
Hi, I cannot seem to get vast-tools to install because devtools fails to install due to git2r failing.

I have tried with R/3.2.0 and R/3.3.2 

I have tries with gcc 4.4.7 and gcc 5.2.0

I always gets what looks like the same seg fault.

Any suggestions?

Thanks,
Doug

installing to /shares/common/users/d.stetner/build/vast/vast-tools/R/Rlib/git2r/libs
** R
** inst
** preparing package for lazy loading
Creating a generic function for 'summary' from package 'base' in package 'git2r'
Creating a generic function for 'diff' from package 'base' in package 'git2r'
Creating a generic function for 'merge' from package 'base' in package 'git2r'
Creating a generic function for 'plot' from package 'graphics' in package 'git2r'
Creating a generic function for 'head' from package 'utils' in package 'git2r'
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
sh: line 1: 44353 Segmentation fault      '/opt/pkg/2015Q2/lib/R/bin/R' --no-save --slave 2>&1 < '/tmp/RtmpjhntFL/filea6e492dc96d'

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(package, c(which.lib.loc, lib.loc))
 4: doTryCatch(return(expr), name, parentenv, handler)
 5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6: tryCatchList(expr, classes, parentenv, handlers)
 7: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
 8: try({    ns <- loadNamespace(package, c(which.lib.loc, lib.loc))    env <- attachNamespace(ns, pos = pos, deps)})
 9: library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE)
10: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
11: suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE))
12: doTryCatch(return(expr), name, parentenv, handler)
13: tryCatchOne(expr, names, parentenv, handlers[[1L]])
14: tryCatchList(expr, classes, parentenv, handlers)
15: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
16: try(suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE)))
17: tools:::.test_load_package("git2r", "/shares/common/users/d.stetner/build/vast/vast-tools/R/Rlib")
aborting ...
ERROR: loading failed
* removing '/shares/common/users/d.stetner/build/vast/vast-tools/R/Rlib/git2r'
make: *** [install] Error 1

**Comment by stetner** [comment]
Program received signal SIGSEGV, Segmentation fault.
0x00002b24fd5da676 in __strcmp_sse42 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-23.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 openssl-1.0.1e-57.el6.x86_64

(gdb) bt
#0  0x00002b24fd5da676 in __strcmp_sse42 () from /lib64/libc.so.6
#1  0x00002b25021812aa in ?? () from /usr/lib64/libcrypto.so.10
#2  0x00002b25021815f6 in lh_insert () from /usr/lib64/libcrypto.so.10
#3  0x00002b250210912b in OBJ_NAME_add () from /usr/lib64/libcrypto.so.10
#4  0x00002b25019b01fa in SSL_library_init () from /opt/pkg/2015Q2/lib/libssl.so.1.0.0
#5  0x00002b25014a20f8 in git_openssl_stream_global_init () at libgit2/src/openssl_stream.c:107
#6  0x00002b2501485fce in git_libgit2_init () from /home/d.stetner/R/x86_64-redhat-linux-gnu-library/3.2/git2r/libs/git2r.so
#7  0x00002b24fcb0b283 in AddDLL () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#8  0x00002b24fcb0b5c8 in do_dynload () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#9  0x00002b24fcbab92c in bcEval () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#10 0x00002b24fcbb21e8 in Rf_eval () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#11 0x00002b24fcbb7315 in Rf_applyClosure () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#12 0x00002b24fcbae773 in bcEval () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#13 0x00002b24fcbb21e8 in Rf_eval () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#14 0x00002b24fcbb7315 in Rf_applyClosure () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#15 0x00002b24fcbae773 in bcEval () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#16 0x00002b24fcbb21e8 in Rf_eval () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#17 0x00002b24fcbb7315 in Rf_applyClosure () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#18 0x00002b24fcbae773 in bcEval () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#19 0x00002b24fcbb21e8 in Rf_eval () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#20 0x00002b24fcbb29a7 in forcePromise () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#21 0x00002b24fcbb2a70 in FORCE_PROMISE () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#22 0x00002b24fcbad6fb in bcEval () from /opt/pkg/2015Q2/lib/R/lib/libR.so
#23 0x00002b24fcbb21e8 in Rf_eval () from /opt/pkg/2015Q2/lib/R/lib/libR.so
---Type <return> to continue, or q <return> to quit---

**Comment by stetner** [comment]
After installing separate:

  1) zlib/1.2.11        2) bzip2/1.0.6        3) xz/5.2.3           4) pcre/8.40          5) openssl/1.1.0f     6) libssh2/1.8.0

and compiling the git2r from source this works.
